import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { AaPanelProvider, type AaPanelSiteSummary } from "@igle/deployer";
import { IgleError, type Actor } from "@igle/shared";
import { ImportService } from "./import-service.js";
import { SiteService } from "./site-service.js";
import { JsonStateStore } from "./state-store.js";
import type { ServerRecord } from "./types.js";

export interface RemoteSiteImportOutcome {
  domain: string;
  status: "imported" | "imported-locked" | "skipped-exists" | "excluded" | "failed";
  siteId?: string;
  warnings?: string[];
  error?: string;
}

interface SiteClassification {
  platform: "static" | "wordpress" | "modx" | "php-dynamic";
  reason?: string;
}

// Extensionless config files aaPanel's editor happily returns as text — GetFileBody's own
// "does not support online editing" refusal already covers everything else, but checking the
// extension first avoids a wasted round-trip for the overwhelming majority of files in a typical
// static site, which are binary (images/fonts).
const TEXT_EXTENSIONS = new Set([
  ".html",
  ".htm",
  ".css",
  ".js",
  ".mjs",
  ".cjs",
  ".json",
  ".xml",
  ".svg",
  ".txt",
  ".md",
  ".csv",
  ".webmanifest",
  ".map",
  ".ini"
]);
const TEXT_BASENAMES = new Set([".htaccess", ".user.ini", "robots.txt", "sitemap.xml"]);

// Not real site content, or regenerated by tooling/the panel itself — skipped while walking the
// remote tree. Confirmed live on a real site: aaPanel's own backup_count/last_backup_time fields
// point at exactly this kind of auto-generated snapshot folder, and one real site's
// "static_backups" directory alone accounted for 9,000+ files (many full historical copies of the
// same site) before this was added — importing those would have bloated the result with stale
// duplicate content, not captured anything real.
const SKIP_DIRECTORY_NAMES = new Set([
  ".git",
  ".well-known",
  "node_modules",
  ".idea",
  ".vscode",
  ".next",
  ".cache",
  "static_backups",
  "backup",
  "backups"
]);

interface StageWarning {
  path: string;
  message: string;
}

export interface RemoteSiteImportProgress {
  domain: string;
  filesProcessed: number;
}

type ProgressCallback = (progress: RemoteSiteImportProgress) => void;
type ResultCallback = (outcome: RemoteSiteImportOutcome) => void;

/**
 * Bounds total concurrent aaPanel requests (directory listings + file reads together) across an
 * entire site's recursive walk — not just within one directory. Walking subdirectories one at a
 * time (await each before starting the next) was the real bottleneck confirmed live: a deep site
 * tree paid full network round-trip latency serially per directory, turning a few thousand files
 * into 25+ minutes for a single site. Firing every subdirectory at once and letting this semaphore
 * queue the excess keeps the server from being hammered while still working the whole tree in
 * parallel.
 */
class Semaphore {
  private active = 0;
  private readonly queue: Array<() => void> = [];

  constructor(private readonly limit: number) {}

  async run<T>(fn: () => Promise<T>): Promise<T> {
    if (this.active >= this.limit) {
      await new Promise<void>((resolve) => this.queue.push(resolve));
    }
    this.active++;
    try {
      return await fn();
    } finally {
      this.active--;
      const next = this.queue.shift();
      if (next) next();
    }
  }
}

/**
 * Pulls a site that's already live on a connected aaPanel server into Igle CMS, reusing
 * ImportService's own directory-import pipeline (page indexing, revisions, metadata) so the
 * result is indistinguishable from a manual zip import.
 *
 * aaPanel's own zip-and-download flow (`/files?action=Zip` + create_download_url) 404s on at
 * least one real panel — confirmed dead even in isolation, most likely blocked at the nginx layer
 * as hardening against a known file-exfiltration vector, since every other `/files?action=...`
 * route on the exact same path prefix works normally. So this walks the site's file tree instead:
 * text files come back through aaPanel's own GetFileBody, and binary assets (which GetFileBody
 * refuses outright) are fetched byte-for-byte from the site's own live public URL — confirmed
 * live to return identical bytes, and universally available for any already-hosted site by
 * definition.
 */
export class RemoteSiteImportService {
  constructor(
    private readonly stateStore: JsonStateStore,
    private readonly siteService: SiteService,
    private readonly importService: ImportService
  ) {}

  /** Every aaPanel-hosted domain not already tracked in Igle CMS, imported one at a time. Slow — intended to run in the background worker, never inline in a request handler. */
  async importAllSitesFromServer(serverId: string, actor: Actor, onProgress?: ProgressCallback, onResult?: ResultCallback): Promise<RemoteSiteImportOutcome[]> {
    const state = await this.stateStore.read();
    const server = state.servers.find((item) => item.id === serverId);
    if (!server) throw new IgleError("SERVER_NOT_FOUND", "That server was not found.", 404);
    if (server.kind !== "aapanel" || !server.baseUrl || !server.apiKey) {
      throw new IgleError("SERVER_MISCONFIGURED", `"${server.name}" isn't an aaPanel server with credentials set.`, 400);
    }

    const provider = new AaPanelProvider({ baseUrl: server.baseUrl, apiKey: server.apiKey });
    const remoteSites = await provider.listSites();
    const existingDomains = new Set(state.sites.map((item) => item.metadata.domain).filter((domain): domain is string => Boolean(domain)));
    const existingSlugs = new Set(state.sites.map((item) => item.slug));
    const excludedDomains = new Set((server.autoImportExcludedDomains ?? []).map((domain) => domain.toLowerCase()));

    const outcomes: RemoteSiteImportOutcome[] = [];
    // A real run confirmed this matters: one oversized site's sustained request volume tripped
    // what looks like rate-limiting on the aaPanel host, and every site attempted afterward
    // failed with the same generic "fetch failed" in rapid succession — burning through the rest
    // of the list for nothing while continuing to hit a server that was already signalling
    // distress. A short pause between sites reduces the chance of tripping it in the first place;
    // the circuit breaker below stops the run once a few in a row fail the same way, leaving the
    // untried remainder for a later "Import sites now" click instead of also failing them.
    let consecutiveFailures = 0;
    for (const remoteSite of remoteSites) {
      if (remoteSite.domain && excludedDomains.has(remoteSite.domain.toLowerCase())) {
        const outcome: RemoteSiteImportOutcome = { domain: remoteSite.domain, status: "excluded" };
        outcomes.push(outcome);
        onResult?.(outcome);
        continue;
      }
      if (!remoteSite.domain || existingDomains.has(remoteSite.domain)) {
        const outcome: RemoteSiteImportOutcome = { domain: remoteSite.domain, status: "skipped-exists" };
        outcomes.push(outcome);
        onResult?.(outcome);
        continue;
      }
      if (consecutiveFailures >= 3) {
        onResult?.({ domain: remoteSite.domain, status: "failed", error: "Stopped early after repeated failures — likely rate-limited by the panel. Try again later." });
        break;
      }
      if (outcomes.length > 0) await new Promise((resolve) => setTimeout(resolve, 2000));
      try {
        const { siteId, warnings, locked } = await this.importOneSite(provider, remoteSite, server, existingSlugs, actor, onProgress);
        existingDomains.add(remoteSite.domain);
        const outcome: RemoteSiteImportOutcome = { domain: remoteSite.domain, status: locked ? "imported-locked" : "imported", siteId, warnings };
        outcomes.push(outcome);
        onResult?.(outcome);
        consecutiveFailures = 0;
      } catch (error) {
        const outcome: RemoteSiteImportOutcome = { domain: remoteSite.domain, status: "failed", error: error instanceof Error ? error.message : "Import failed." };
        outcomes.push(outcome);
        onResult?.(outcome);
        consecutiveFailures += 1;
      }
    }
    return outcomes;
  }

  /**
   * Called on a timer from apps/worker — finds every aaPanel server flagged autoImportStatus
   * "pending" (set the instant a server is added, or when an admin clicks "Import sites now") and
   * runs its import, persisting progress on the ServerRecord itself so the Servers page can show
   * it without any separate job-tracking store. Never called from a request handler: a shared VPS
   * can host dozens of sites, and a full import can run well past any reasonable HTTP timeout.
   */
  async processPendingImports(onProgress?: ProgressCallback, onResult?: ResultCallback): Promise<void> {
    const state = await this.stateStore.read();
    const pendingServerIds = state.servers.filter((server) => server.kind === "aapanel" && server.autoImportStatus === "pending").map((server) => server.id);
    for (const serverId of pendingServerIds) {
      await this.processOneServer(serverId, onProgress, onResult);
    }
  }

  private async processOneServer(serverId: string, onProgress?: ProgressCallback, onResult?: ResultCallback): Promise<void> {
    const state = await this.stateStore.read();
    const server = state.servers.find((item) => item.id === serverId);
    if (!server || server.autoImportStatus !== "pending") return;

    const actor: Actor = {
      id: server.autoImportActorId ?? "system",
      email: server.autoImportActorEmail ?? "system@igle.local",
      role: "administrator"
    };

    await this.stateStore.update((next) => {
      const record = next.servers.find((item) => item.id === serverId);
      if (record) {
        record.autoImportStatus = "running";
        record.autoImportStartedAt = new Date().toISOString();
        record.autoImportFinishedAt = undefined;
      }
    });

    try {
      const outcomes = await this.importAllSitesFromServer(serverId, actor, onProgress, onResult);
      await this.stateStore.update((next) => {
        const record = next.servers.find((item) => item.id === serverId);
        if (record) {
          record.autoImportStatus = "done";
          record.autoImportFinishedAt = new Date().toISOString();
          record.autoImportSummary = summarize(outcomes);
        }
      });
    } catch (error) {
      await this.stateStore.update((next) => {
        const record = next.servers.find((item) => item.id === serverId);
        if (record) {
          record.autoImportStatus = "failed";
          record.autoImportFinishedAt = new Date().toISOString();
          record.autoImportSummary = {
            imported: 0,
            locked: 0,
            skipped: 0,
            excluded: 0,
            failed: 0,
            errors: [{ domain: "", message: error instanceof Error ? error.message : "Import failed." }]
          };
        }
      });
    }
  }

  private async importOneSite(
    provider: AaPanelProvider,
    remoteSite: AaPanelSiteSummary,
    server: ServerRecord,
    existingSlugs: Set<string>,
    actor: Actor,
    onProgress?: ProgressCallback
  ): Promise<{ siteId: string; warnings: string[]; locked: boolean }> {
    const stagingDir = await fs.mkdtemp(path.join(os.tmpdir(), "igle-remote-import-"));
    const warnings: StageWarning[] = [];
    try {
      // Classified from aaPanel's own root listing — one cheap extra call, done up front so the
      // platform/lock reason is known before anything else, rather than re-walking the tree a
      // second time after staging.
      const classification = await classifyRemoteSite(provider, remoteSite.documentRoot);

      // Probed once per site rather than per file: on a shared VPS where many older sites never
      // got an SSL cert, trying HTTPS first for every single binary asset means every one of them
      // eats a full connect timeout before falling back to HTTP — confirmed live, where this
      // turned a handful of minutes into a 12+ minute stall on just one site's assets.
      const protocol = await probeSiteProtocol(remoteSite.domain);
      // Kept modest — this hits a real production server serving live traffic, not a sandbox.
      // Confirmed live: sustained heavy concurrency (12) plus incidental extra diagnostic
      // requests produced a transient "fetch failed" that aborted an otherwise-healthy site's
      // import partway through.
      const semaphore = new Semaphore(6);
      let filesProcessed = 0;
      await stageRemoteDirectory(provider, remoteSite.domain, protocol, remoteSite.documentRoot, stagingDir, "", warnings, semaphore, () => {
        filesProcessed += 1;
        if (onProgress && filesProcessed % 25 === 0) onProgress({ domain: remoteSite.domain, filesProcessed });
      });
      if (onProgress) onProgress({ domain: remoteSite.domain, filesProcessed });

      const slug = uniqueSlug(remoteSite.domain, existingSlugs);
      existingSlugs.add(slug);
      const site = await this.siteService.createBlankSite({ name: remoteSite.domain, slug }, actor);
      await this.importService.importDirectory(site, stagingDir, actor);
      // Always wire up the server assignment (and the platform classification/lock) — none of
      // that is ever invalid input, unlike the domain below. This is also the point a dynamic
      // site actually becomes locked: importDirectory just ran against a brand-new, still-
      // unlocked site, so the content-lock guard never blocked staging its own content in.
      await this.siteService.updateSettings(
        site,
        {
          deploymentTarget: "aapanel",
          serverId: server.id,
          platform: classification.platform,
          contentLocked: classification.platform !== "static",
          contentLockReason: classification.reason
        },
        actor
      );
      try {
        await this.siteService.updateSettings(site, { domain: remoteSite.domain }, actor);
      } catch (error) {
        warnings.push({
          path: "(site domain)",
          message: `Imported the content, but couldn't set the domain to "${remoteSite.domain}": ${error instanceof Error ? error.message : "unknown error"}. Set it manually in Site Settings.`
        });
      }

      return {
        siteId: site.id,
        warnings: warnings.map((warning) => `${warning.path}: ${warning.message}`),
        locked: classification.platform !== "static"
      };
    } finally {
      await fs.rm(stagingDir, { recursive: true, force: true });
    }
  }
}

async function stageRemoteDirectory(
  provider: AaPanelProvider,
  domain: string,
  protocol: "https" | "http",
  remoteRoot: string,
  localRoot: string,
  relative: string,
  warnings: StageWarning[],
  semaphore: Semaphore,
  onFileDone: () => void
): Promise<void> {
  // A directory listing that fails aborts every file and subdirectory beneath it (unlike one
  // failed file, which just becomes a warning) — confirmed live, a single transient "fetch
  // failed" here lost the rest of an otherwise-successful, thousands-of-files-deep site import.
  // Retried a couple of times with a short backoff before giving up.
  const listing = await semaphore.run(() => withRetries(() => provider.listDirectory(path.posix.join(remoteRoot, relative)), 3));
  await fs.mkdir(path.join(localRoot, relative), { recursive: true });

  const fileWork = listing.files.map((file) =>
    semaphore.run(async () => {
      const relativeFilePath = path.posix.join(relative, file.name);
      const localFilePath = path.join(localRoot, relativeFilePath);
      try {
        if (isTextFile(file.name)) {
          const text = await provider.readTextFile(path.posix.join(remoteRoot, relativeFilePath));
          if (text !== undefined) {
            await fs.writeFile(localFilePath, text, "utf8");
            return;
          }
        }
        const bytes = await fetchLiveAsset(domain, protocol, relativeFilePath);
        if (bytes) {
          await fs.writeFile(localFilePath, bytes);
        } else {
          warnings.push({ path: relativeFilePath, message: "Could not read this file from the panel or fetch it from the live site." });
        }
      } catch (error) {
        warnings.push({ path: relativeFilePath, message: error instanceof Error ? error.message : "Unknown error." });
      } finally {
        onFileDone();
      }
    })
  );

  // Every subdirectory is kicked off together rather than awaited one at a time — the shared
  // semaphore (not this fan-out) is what actually bounds concurrent aaPanel requests, so this is
  // safe even for a wide/deep tree and is what turns network round-trip latency from a serial,
  // per-directory tax into something paid mostly in parallel.
  const dirWork = listing.directories
    .filter((dirName) => !SKIP_DIRECTORY_NAMES.has(dirName))
    .map((dirName) => stageRemoteDirectory(provider, domain, protocol, remoteRoot, localRoot, path.posix.join(relative, dirName), warnings, semaphore, onFileDone));

  await Promise.all([...fileWork, ...dirWork]);
}

async function withRetries<T>(fn: () => Promise<T>, attempts: number): Promise<T> {
  let lastError: unknown;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      return await fn();
    } catch (error) {
      lastError = error;
      if (attempt < attempts) await new Promise((resolve) => setTimeout(resolve, 500 * attempt));
    }
  }
  throw lastError;
}

/**
 * Classifies a site as static (safe for Igle CMS to edit/deploy) or one of a few dynamic,
 * database-driven CMS platforms Igle CMS only ever sees a stale file snapshot of — confirmed
 * live against real aaPanel-hosted sites, including one genuine WordPress install and one MODX
 * install (identifiable by its `manager`/`connectors`/`core` top-level layout). A single
 * `GetDir` call against the document root is enough; there's no need to walk the rest of the tree
 * just to decide this.
 */
async function classifyRemoteSite(provider: AaPanelProvider, remoteRoot: string): Promise<SiteClassification> {
  const listing = await provider.listDirectory(remoteRoot);
  const dirs = new Set(listing.directories);
  const files = new Set(listing.files.map((file) => file.name));

  if (files.has("wp-config.php") || (dirs.has("wp-content") && dirs.has("wp-includes"))) {
    return { platform: "wordpress", reason: "WordPress site detected — imported for reference only. Editing and deploying are disabled to avoid breaking the live install." };
  }
  if (dirs.has("manager") && dirs.has("connectors") && (dirs.has("core") || files.has("config.core.php"))) {
    return { platform: "modx", reason: "MODX site detected — imported for reference only. Editing and deploying are disabled to avoid breaking the live install." };
  }
  if (files.has("index.php") && !files.has("index.html") && !files.has("index.htm")) {
    return { platform: "php-dynamic", reason: "Dynamic (PHP-driven) site detected — imported for reference only. Editing and deploying are disabled to avoid breaking the live install." };
  }
  return { platform: "static" };
}

/** One cheap connectivity check per site, so per-file fetches never pay for trying a dead protocol. */
async function probeSiteProtocol(domain: string): Promise<"https" | "http"> {
  try {
    await fetch(`https://${domain}/`, { method: "HEAD", signal: AbortSignal.timeout(6000) });
    return "https";
  } catch {
    return "http";
  }
}

function isTextFile(filename: string): boolean {
  if (TEXT_BASENAMES.has(filename)) return true;
  return TEXT_EXTENSIONS.has(path.extname(filename).toLowerCase());
}

/**
 * Binary assets have no confirmed raw-download route through aaPanel's API (see the class
 * docstring) — fetched from the site's own live URL instead, which works for any already-hosted
 * site by definition. `preferredProtocol` comes from one probe per site (probeSiteProtocol), not
 * tried fresh per file — the fallback here only fires for a genuinely per-file mismatch (e.g. one
 * asset served from a different, http-only subdomain), which is rare.
 */
async function fetchLiveAsset(domain: string, preferredProtocol: "https" | "http", relativePath: string): Promise<Buffer | undefined> {
  const encodedPath = `/${relativePath
    .split("/")
    .map((segment) => encodeURIComponent(segment))
    .join("/")}`;
  const protocols = preferredProtocol === "https" ? (["https", "http"] as const) : (["http", "https"] as const);
  for (const protocol of protocols) {
    try {
      const response = await fetch(`${protocol}://${domain}${encodedPath}`, { signal: AbortSignal.timeout(15000) });
      if (response.ok) return Buffer.from(await response.arrayBuffer());
    } catch {
      // try the next protocol
    }
  }
  return undefined;
}

function summarize(outcomes: RemoteSiteImportOutcome[]): NonNullable<ServerRecord["autoImportSummary"]> {
  return {
    imported: outcomes.filter((outcome) => outcome.status === "imported" || outcome.status === "imported-locked").length,
    locked: outcomes.filter((outcome) => outcome.status === "imported-locked").length,
    skipped: outcomes.filter((outcome) => outcome.status === "skipped-exists").length,
    excluded: outcomes.filter((outcome) => outcome.status === "excluded").length,
    failed: outcomes.filter((outcome) => outcome.status === "failed").length,
    errors: outcomes
      .filter((outcome): outcome is RemoteSiteImportOutcome & { error: string } => outcome.status === "failed" && Boolean(outcome.error))
      .map((outcome) => ({ domain: outcome.domain, message: outcome.error }))
  };
}

function uniqueSlug(domain: string, existing: Set<string>): string {
  const base = domain.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "site";
  let candidate = base;
  let suffix = 2;
  while (existing.has(candidate)) {
    candidate = `${base}-${suffix}`;
    suffix += 1;
  }
  return candidate;
}
